import Navigation from "../components/Navigation";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SearcHub",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    
  return (
    <html lang="en" className="bg-slate-900">
      <body className={inter.className}>

        <div className="lg:w-[700px] md:w-[600px] w-[350px] mx-auto">
          <Navigation />
          {children}
        </div>

      </body>
    </html>
  );
}
